default:
  image: python:3.10

variables:
  APP: "dosimeter"

before_script:
  - pip install --upgrade pip
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install

stages:
  - quality
  - typing
  - tests

isort:
  stage: quality
  script:
    - echo "Running the Static Analysis stage..."
    - poetry run isort .
  retry:
    max: 2
    when: runner_system_failure

ruff:
  stage: quality
  script:
    - poetry run ruff ${APP}/*.py
  retry:
    max: 2
    when: runner_system_failure

black:
  stage: quality
  script:
    - poetry run black .
    - echo "linting done!"
  retry:
    max: 2
    when: runner_system_failure

mypy:
  stage: typing
  needs: [isort, black, ruff]
  script:
    - echo "Running the Type checking stage..."
    - poetry run mypy .
    - echo "Type checking done!"

unit-tests:
  stage: tests
  needs: [isort, black, ruff, mypy]
  script:
    - echo "Running the Tests stage..."
    - poetry run pytest --cov=${APP} --cov-report=term --cov-report=html
    - echo "Testing done!"
  coverage: '/^TOTAL.+?(\d{2}\.\d{2}\%)$/'
  artifacts:
    paths:
      - coverage/
    expire_in: 30 days
  retry:
    max: 2
    when: runner_system_failure
