default:
  image: python:3.10

variables:
  APP: "dosimeter"

before_script:
  - pip install --upgrade pip
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install

stages:
  - Static Analysis
  - Type checking
  - Tests

isort:
  stage: Static Analysis
  script:
    - echo "Running the Static Analysis stage..."
    - poetry run isort .

flake8:
  stage: Static Analysis
  script:
    - poetry run flake8 ${APP}/*.py

black:
  stage: Static Analysis
  script:
    - poetry run black .
    - echo "linting done!"

mypy:
  stage: Type checking
  needs: [isort, flake8, black]
  script:
    - echo "Running the Type checking stage..."
    - poetry run mypy .
    - echo "Type checking done!"

unit-tests:
  stage: Tests
  needs: [isort, flake8, black, mypy]
  script:
    - echo "Running the Tests stage..."
    - poetry run pytest --cov=${APP} --cov-report=html
    - echo "Testing done!"
  artifacts:
    paths:
      - coverage
    expire_in: 30 days
