repos:
# Fixes the spaces
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
# isort sorts the imports
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      name: isort (python)
      args: [--settings-path=pyproject.toml]
# Flake8 lints the Python code
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      args: [--config=setup.cfg]
      additional_dependencies: [
        "flake8-bugbear",
        "flake8-builtins",
        "flake8-broken-line",
        "flake8-tidy-imports",
        "flake8-coding",
      ]
# Black formats the Python code
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3
      args: [--config=pyproject.toml]
# mypy checks types
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    - id: mypy
      name: mypy
      exclude: ^(tests/)
